server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:db;
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop