CREATE TABLE tb_answered_question_user
(
    question_id     BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    answered_status VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_answered_question_user PRIMARY KEY (question_id, user_id)
);

CREATE TABLE tb_question
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id           BIGINT                                  NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    question             TEXT                                    NOT NULL,
    option1              TEXT                                    NOT NULL,
    option2              TEXT                                    NOT NULL,
    option3              TEXT                                    NOT NULL,
    option4              TEXT                                    NOT NULL,
    correct_option       INTEGER                                 NOT NULL,
    level                VARCHAR(255)                            NOT NULL,
    answer_count         INTEGER                                 NOT NULL,
    correct_answer_count INTEGER                                 NOT NULL,
    tag_id               BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_question PRIMARY KEY (id)
);

CREATE TABLE tb_related_questions
(
    question_id BIGINT NOT NULL,
    related_id  BIGINT NOT NULL
);

CREATE TABLE tb_tag
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    question_number INTEGER                                 NOT NULL,
    CONSTRAINT pk_tb_tag PRIMARY KEY (id)
);

CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    score    INTEGER                                 NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_tag
    ADD CONSTRAINT uc_tb_tag_name UNIQUE (name);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_name UNIQUE (name);

ALTER TABLE tb_answered_question_user
    ADD CONSTRAINT FK_TB_ANSWERED_QUESTION_USER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES tb_question (id);

ALTER TABLE tb_answered_question_user
    ADD CONSTRAINT FK_TB_ANSWERED_QUESTION_USER_ON_USER FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_question
    ADD CONSTRAINT FK_TB_QUESTION_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES tb_user (id);

ALTER TABLE tb_question
    ADD CONSTRAINT FK_TB_QUESTION_ON_TAG FOREIGN KEY (tag_id) REFERENCES tb_tag (id);

ALTER TABLE tb_related_questions
    ADD CONSTRAINT fk_tbrelque_on_question FOREIGN KEY (question_id) REFERENCES tb_question (id);

ALTER TABLE tb_related_questions
    ADD CONSTRAINT fk_tbrelque_on_related FOREIGN KEY (related_id) REFERENCES tb_question (id);